name: 'Bage: Code Lines Count'
description: 'Count lines of code and create a badge for display result'
inputs:
  include-files:
    description: 'Count lines in files (posix-egrep regex)'
    required: true
    default: '.*\**'
  exclude-files:
    description: 'Do not count lines in files (posix-egrep regex)'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Count lines of code and generate badge
      id: counter
      run: |
        mkdir ./output
        pip install anybadge
        $GITHUB_ACTION_PATH/generate-badge.sh $INCLUDE_FILES $EXCLUDE_FILES
      shell: bash
      env:
        INCLUDE_FILES: ${{ inputs.include-files }}
        EXCLUDE_FILES: ${{ inputs.exclude-files }}
