name: 'Code Lines Counter'
description: 'Count lines of code'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  include-files:
    description: 'Count lines in files (posix-egrep regex)'
    required: true
    default: '.*\**'
  exclude-files:
    description: 'Do not count lines in files (posix-egrep regex)'
    required: true
    default: ''
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Count lines in the files
      run: count.sh $INCLUDE_FILES $EXCLUDE_FILES
      shell: bash

    - name: Count lines in the files
      run: count.sh $INCLUDE_FILES $EXCLUDE_FILES
      shell: bash
      env:
        INCLUDE_FILES: ${{ inputs.include-files }}
        EXCLUDE_FILES: ${{ inputs.exclude-files }}
