on: [push]

jobs:
  lines_counter_job:
    runs-on: ubuntu-latest
    name: A job to count lines of code
    steps:
      - uses: actions/checkout@v4
      - id: counting
        uses: ./
        with:
          include-files: '.*\.sh'
#      - run: echo random-number "$RANDOM_NUMBER"
#        shell: bash
#        env:
#          RANDOM_NUMBER: ${{ steps.counting.outputs.random-number }}