on: [push]

jobs:
  tests_job:
    name: Test scripts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
      - uses: articulate/actions-markdownlint@v1.1.0

